language: php
branches:
  only: master
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script: composer install
script:
  - mkdir -p build/logs
  - phpunit tests/
after_script:
 - php vendor/bin/coveralls -v